### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by theDyingMountain** [m-vo/contao-nested-forms#1]
I get the following error message when creating a nested form element. I use nested-forms in combination with [leads ](https://github.com/terminal42/contao-leads) and [conditional form fields](https://github.com/terminal42/contao-conditionalformfields)

`The service "mvo_contao_nested_forms.listener.datacontainer.form_field" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services`

**Comment by m-vo** [comment]
Which contao version are you using?

**Comment by theDyingMountain** [comment]
4.6.13

**Comment by m-vo** [comment]
fixed in f780ea29cdf6443ac1162577685332ad5e917903
